export default {
  "bg-page": "var(--gray-950)",
  "bg-surface": "var(--gray-900)",
  "bg-floating": "var(--gray-850)",
  "bg-gray-solid": "var(--gray-700)",
  "bg-gray-solid-hovered": "var(--gray-600)",
  "bg-gray-solid-pressed": "color-mix(in srgb, var(--gray-600), var(--white) 5%)",
  "bg-gray-subtle": "var(--gray-800)",
  "bg-gray-subtle-hovered": "var(--gray-750)",
  "bg-gray-subtle-pressed": "color-mix(in srgb, var(--gray-750), var(--white) 3%)",
  "bg-brand-solid": "var(--brand-700)",
  "bg-brand-solid-hovered": "var(--brand-600)",
  "bg-brand-solid-pressed": "color-mix(in srgb, var(--brand-600), var(--white) 5%)",
  "bg-brand-subtle": "var(--brand-950)",
  "bg-brand-subtle-hovered": "var(--brand-900)",
  "bg-brand-subtle-pressed": "color-mix(in srgb, var(--brand-900), var(--white) 3%)",
  "bg-transparent": "var(--transparent)",
  "bg-transparent-hovered": "color-mix(in hsl, var(--gray-750), var(--transparent) 20%)",
  "bg-transparent-pressed": "color-mix(in hsl, var(--gray-750), var(--transparent) 5%)",
  "bg-transparent-brand": "var(--transparent)",
  "bg-transparent-brand-hovered": "color-mix(in srgb, var(--brand-900), var(--transparent) 50%)",
  "bg-transparent-brand-pressed": "color-mix(in srgb, var(--brand-900), var(--transparent) 40%)",
  "bg-selected": "color-mix(in srgb, var(--brand-900), var(--transparent) 70%)",
  "bg-disabled": "var(--gray-800)",
  "fg-neutral": "var(--gray-100)",
  "fg-neutral-bold": "var(--gray-50)",
  "fg-neutral-muted": "var(--gray-300)",
  "fg-neutral-subtle": "var(--gray-400)",
  "fg-neutral-subtlest": "var(--gray-500)",
  "fg-gray": "var(--gray-400)",
  "fg-gray-contrast": "var(--gray-200)",
  "fg-brand": "var(--brand-500)",
  "fg-brand-contrast": "var(--brand-200)",
  "fg-error": "red",
  "fg-selected": "var(--brand-400)",
  border: "var(--gray-800)",
  "border-gray": "var(--gray-700)",
  "border-gray-bold": "var(--gray-600)",
  "border-brand": "var(--brand-900)",
  "border-brand-bold": "var(--brand-800)",
  "border-error": "red",
  "border-selected": "var(--brand-400)",
};
