name: Vercel Preview Deployment

env:
  GITHUB_OWNER: kwonjuhee
  GITHUB_REPO: notes-backup
  GITHUB_AUTH: ${{ secrets.GH_AUTH }}
  MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

on:
  push:
    branches:
      - deploy-test
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Generate env file
        run: |
          echo "GITHUB_OWNER=$GITHUB_OWNER" >> .env
          echo "GITHUB_REPO=$GITHUB_REPO" >> .env
          echo "GITHUB_AUTH=$GITHUB_AUTH" >> .env
          echo "MY_PASSWORD=$MY_PASSWORD" >> .env
          echo "JWT_SECRET_KEY=$JWT_SECRET_KEY" >> .env
          
      - name: Build project
        run: npm run build

      - name: Deploy preview
        run: npx vercel --token $VERCEL_TOKEN
